//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Generes
{
    public int id { get; set; }
    public string name { get; set; }
}

public partial class Puntuacions
{
    public int id_usuari { get; set; }
    public int id_serie { get; set; }
    public Nullable<decimal> score { get; set; }
    public int id { get; set; }

    public virtual Series Series { get; set; }
    public virtual Usuaris Usuaris { get; set; }
}

public partial class Series
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Series()
    {
        this.Usuaris = new HashSet<Usuaris>();
        this.Puntuacions = new HashSet<Puntuacions>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string genre { get; set; }
    public string plot { get; set; }
    public Nullable<decimal> score { get; set; }
    public Nullable<int> year_of_release { get; set; }
    public Nullable<int> times_rated { get; set; }
    public string img_src { get; set; }
    public Nullable<decimal> total_score { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Usuaris> Usuaris { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Puntuacions> Puntuacions { get; set; }
}

public partial class Usuaris
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Usuaris()
    {
        this.Series = new HashSet<Series>();
        this.Puntuacions = new HashSet<Puntuacions>();
    }

    public int id_usuari { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> data_naixement { get; set; }
    public string genere { get; set; }
    public string img_src { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Series> Series { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Puntuacions> Puntuacions { get; set; }
}
